# Generated by Django 4.2.4 on 2023-08-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpdapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserregistration',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
