# Generated by Django 4.2.4 on 2023-08-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpdapp', '0002_alter_customuserregistration_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserregistration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
