# Generated by Django 4.2.4 on 2023-08-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpdapp', '0004_keyvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyvalue',
            name='key',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
