# Generated by Django 4.2.4 on 2023-08-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpdapp', '0005_alter_keyvalue_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyvalue',
            name='value',
            field=models.CharField(max_length=10000),
        ),
    ]
